### ISSUE TITLE
libmagick missing in docker image

### ISSUE THREAD

**Issue by rvanguri** [drieslab/Giotto#159]
Hi,

I pulled the latest docker image delron01/giotto:latest and it seems that libMagick is missing:

visium = createGiottoVisiumObject(visium_dir = data_path, expr_data = 'raw',
                                        png_name = 'tissue_lowres_image.png',
                                        gene_column_index = 2, instructions = instrs)

A structured visium directory will be used 
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/local/lib/R/site-library/magick/libs/magick.so':
  libMagick++-6.Q16.so.8: cannot open shared object file: No such file or directory

Any help would be appreciated, thanks!

**Comment by RubD** [comment]
I believe this is not an issue anymore in the more recent versions of Giotto and the docker image.
